# Generated by Django 4.2.8 on 2023-12-10 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RSSFeed",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, unique=True)),
                ("url", models.URLField(max_length=2000, unique=True)),
                ("is_enabled", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="RSSItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("guid", models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TelegramSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("api_key", models.CharField(max_length=200)),
                ("chat_id", models.CharField(max_length=200)),
                ("is_enabled", models.BooleanField(default=True)),
                ("rss_feed", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rss_handler.rssfeed")),
            ],
        ),
        migrations.CreateModel(
            name="GPTPromptSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prompt_name", models.CharField(max_length=200)),
                ("prompt_text", models.TextField()),
                ("is_enabled", models.BooleanField(default=True)),
                ("rss_feed", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rss_handler.rssfeed")),
            ],
        ),
        migrations.CreateModel(
            name="GoogleChatSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chat_name", models.CharField(max_length=200)),
                ("webhook_url", models.URLField(max_length=2000)),
                ("is_enabled", models.BooleanField(default=True)),
                ("rss_feed", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rss_handler.rssfeed")),
            ],
        ),
        migrations.CreateModel(
            name="FiberyCRMSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fibery_url", models.URLField(max_length=2000)),
                ("is_enabled", models.BooleanField(default=True)),
                ("rss_feed", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rss_handler.rssfeed")),
            ],
        ),
    ]
